[package]
name = "code_snippet_generator"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro-error = "1.0.4"
quote = "1.0.18"
rustfmt-wrapper = "0.1.0"
syn = "1.0.96"
synoptic = "1.2.0"
web-sys = "0.3.57"

[features]
html = []
